- hosts: grafana
  become: yes
  gather_facts: true
  roles:
    - role: cloudalchemy.grafana
      vars:
        grafana_version: latest
        grafana_security:
          admin_user: admin
          admin_password: "12345" 
        grafana_datasources:
          - name: prometheus
            type: prometheus
            access: proxy
            url: "http://{{ groups['prometheus'][0] }}:9090"
            basicAuth: false
