#---
#- name: Configure webserver with nginx
#  hosts: web
#  become: True
#  tasks:
#    - name: install nginx
#      apt: name=nginx update_cache=yes
#    - name: copy nginx config file
#      copy: src=files/nginx.conf dest=/etc/nginx/sites-available/default
#    - name: enable configuration
#      file: >
#        dest=/etc/nginx/sites-enabled/default
#        src=/etc/nginx/sites-available/default
#        state=link
#    - name: copy index.html
#      template: src=templates/index.html.j2 dest=/usr/share/nginx/html/index.html mode=0644
#    - name: restart nginx
#      service: name=nginx state=restarted
#    - name: Check a status 200
#      uri:
#        url: http://localhost   
#        status_code: 200
#      register: this
#
#    - debug:
#        msg: '{{ this }}'      
#      


---
- name: Configure webserver with nginx
  hosts: web
  become: True
  tasks:
    
    - name: install nginx
      apt: name=nginx update_cache=yes
      
    - name: copy nginx config file
      copy: src=files/nginx.conf dest=/etc/nginx/sites-available/default
      
    - name: enable configuration
      file: >
        dest=/etc/nginx/sites-enabled/default
        src=/etc/nginx/sites-available/default
        state=link
        
    - name: "copy custom config"
      copy:
        src: ./files/custom_conf/nginx.conf 
        dest: /etc/nginx/
#      notify: restart nginx        
        
    - name: copy index.html
      template: src=templates/index.html.j2 dest=/usr/share/nginx/html/index.html mode=0644

    - name: restart nginx
      service: name=nginx state=restarted
      
    - name: Check a status 200
      uri:
        url: http://localhost  
        status_code: 200
      register: this

    - debug:
        msg: '{{ this }}'      
      
